spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8180/realms/Demo-Realm"
          #jwk-set-uri: "http://keycloak:8080/realms/Demo-Realm/protocol/openid-connect/certs"
          jwk-set-uri: "http://localhost:8180/realms/Demo-Realm/protocol/openid-connect/certs"