version: "3.8"

volumes:
  db:

services:
  keycloak-db:
    image: postgres:14.5
    volumes:
      - ./keycloak_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.1
    ports:
      - '8180:8080'
    depends_on:
      - keycloak-db
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      DB_VENDOR: postgres
      DB_ADDR: keycloak-db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    entrypoint: [ "/opt/keycloak/bin/kc.sh", "--verbose start-dev" ]

  db:
    image: postgres:14.5
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: endpointmonitor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  endpointmonitor:
    image: endpoint-monitor-img
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - keycloak
      - db
    ports:
      - '8080:8080'
    restart: always  
