version: "3.8"

configs:
  web-config:
    file: ./application.yml

services:
  db:
    image: postgres:14.5
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: automotive
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      test:
  keycloakdb:
    image: postgres:14.5
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      test:
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.1
    ports:
      - '8180:8080'
    depends_on:
      - keycloakdb
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloakdb:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      DB_VENDOR: postgres
      DB_ADDR: keycloakdb
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    entrypoint: ["/opt/keycloak/bin/kc.sh", "--verbose start-dev"]
    networks:
      test:
  #serv-python:
  #  image: python:3.5.2
  #  network_mode: bridge
  #  entrypoint: /usr/bin/yes
  #  networks:
  #    test:
  web:
    build: .
    depends_on:
      - keycloak
      - db
    configs:
      - source: web-config
        target: /app/application.yml
    environment:
      SPRING_CONFIG_LOCATION: 'file:///app/application.yml'
    ports:
      - "8081:8080"
    networks:
      test:

networks:
  test:
    driver: bridge