version: "3.8"

services:
  db:
    image: postgres:14.5
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: endpointmonitor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  #serv-python:
  #  image: python:3.5.2
  #  network_mode: bridge
  #  entrypoint: /usr/bin/yes